apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: qa_to_dev
  namespace: dev
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: edit
subjects:
  - kind: ServiceAccount
    name: qa
    namespace: prod