apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: qa_to_prod
  namespace: prod
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: view
subjects:
  - kind: ServiceAccount
    name: qa
    namespace: prod