
apiVersion: v1
kind: ConfigMap
metadata:
  name: rabbitmq-dev-server-conf
  namespace: dev
  labels: 
    app.kubernetes.io/component=rabbitmq
    app.kubernetes.io/name=rabbitmq-dev
    app.kubernetes.io/part-of=rabbitmq
data:
  enabled_plugins: |
    [rabbitmq_peer_discovery_k8s, rabbitmq_management, rabbitmq_prometheus, rabbitmq_shovel].