apiVersion: v1
kind: ConfigMap
metadata:
  annotations:
  labels:
    app: app.kubernetes.io/name=ingress-ngin
  name: nginx-configuration
  namespace: ingress-nginx
data:
  use-forwarded-headers: "true"
  compute-full-forwarded-for: "true"
  use-proxy-protocol: "true"