---
    apiVersion: v1
    kind: ConfigMap
    metadata:
      name: my-configmap-secret
    data:
      default-secret.conf: |
        server {
            listen       80 default_server;
            server_name  _;
    
            default_type text/plain;
    
            location /secret {
              alias /opt;
            }
            location / {
                return 200 '$hostname request: $request_uri\n';
            }
        }