apiVersion: v1
kind: Namespace
metadata:
  name: mcx

---

apiVersion: v1
kind: Secret
metadata:
  name: database-config
  namespace: mcx
stringData:
  HOST: mgp-db.fors.ru
  PORT: "5432"
  DATABASE: mgp
  USERNAME: postgres
  PASSWORD: postgres

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: support-agreement
  namespace: mcx
spec:
  replicas: 3
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: support-agreement
      service: support-agreement
  template:
    metadata:
      name: mcx
      labels:
        app: support-agreement
        service: support-agreement
    spec:
      containers:
        - image: nexus.fors.ru:10442/mcx/mgp-support-agreement:latest
          name: support-agreement
          imagePullPolicy: Always
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8080
            initialDelaySeconds: 20
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8080
            initialDelaySeconds: 20
          ports:
            - name: app-port
              containerPort: 8080
          envFrom:
            - prefix: DB_
              secretRef:
                name: database-config
---

apiVersion: v1
kind: Service
metadata:
  name: support-agreement
  namespace: mcx
spec:
  type: NodePort
  selector:
    app: support-agreement
    service: support-agreement
  ports:
    - nodePort: 30561
      port: 80
      targetPort: 8080
