apiVersion: v1
kind: Service
metadata:
  name: subject-service
spec:
  type: NodePort
  selector:
    app: subject-service
  ports:
    - port: 80
      targetPort: 8091
      protocol: TCP
      name: http
      nodePort: 30123