apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic 
metadata:
  name: mgp-nsi-demo.public.nsi-class
  labels:
    strimzi.io/cluster: kafka
spec: 
  topicName: mgp_nsi_demo.public.nsi_class
  partitions: 1
  replicas: 1
  config:
    retention.ms: -1
    segment.bytes: 1073741824