apiVersion: v1
kind: PersistentVolume
metadata:
  name: data-kafka-zookeeper-1
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteMany
  claimRef:
    kind: PersistentVolumeClaim
    namespace: prod
    name: data-kafka-zookeeper-1
  persistentVolumeReclaimPolicy: Retain
  #storageClassName: zookeeper-prod
  nfs:
    server: drbd-cluster.tr.local
    path: /data/kafka3