apiVersion: rabbitmq.com/v1beta1
kind: RabbitmqCluster
metadata:
    name: rabbitmq
spec:
  service:
    type: NodePort


  replicas: 1
  persistence:
   storageClassName: persistence-rabbitmq-server
  resources:
    requests:
      cpu: 256m
      memory: 1024Mi
    limits:
      cpu: 256m
      memory: 1024Mi
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: kubernetes.io/hostname
            operator: In
            values:
            - mgp-test-node2.fors.ru