kind: PersistentVolume
apiVersion: v1
metadata:
  name: persistence-rabbitmq-server
  labels:
    type: local
  annotations:
    volume.alpha.kubernetes.io/storage-class: persistence-rabbitmq-server
spec:
  storageClassName: persistence-rabbitmq-server
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
  hostPath:
    path: "/opt/persistence-rabbitmq-server"
