apiVersion: v1
kind: ServiceAccount
metadata:
  name: runner-gitlab-runner
  namespace: gitlab-managed-apps

apiVersion: rbac.authorization.k8s.io/v1
kind: "Role"
metadata:
  name: runner-gitlab-runner
  labels:
    app: runner-gitlab-runner
    chart: gitlab-runner-0.21.1
    release: "gitlab-runner"
    heritage: "Helm"
rules:
- apiGroups: [""]
  resources: ["*"]
  verbs: ["*"]

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: default_runner-gitlab-runner
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: runner-gitlab-runner
subjects:
  - kind: ServiceAccount
    name: runner-gitlab-runner
    namespace: gitlab-managed-apps
