apiVersion: rbac.authorization.k8s.io/v1beta1
kind: RoleBinding
metadata:
  name: default_runner-gitlab-runner
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: runner-gitlab-runner
subjects:
  - kind: ServiceAccount
    name: default
    namespace: gitlab-managed-apps
