apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-pvc-2
  namespace: kafka
spec:
  storageClassName: kafka-storage
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Mi