apiVersion: v1
kind: PersistentVolume
metadata:
  name: local-pv-for-zookeeper-dev-mgp3
spec:
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-pv-for-zookeeper-dev-mgp3
  local:
    path: /opt/zookeeper
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - mgp3.fors.ru