apiVersion: kafka.strimzi.io/v1beta2
kind: Kafka
metadata:
  name: kafka
spec:
  kafka:
    replicas: 1
 #   resources: 
 #     requests:
 #       memory: 256Mi
 #       cpu: "100m"
 #     limits:
 #       memory: 512Mi
 #       cpu: "1"
    listeners:
      - name: plain
        port: 9092
        type: internal
        tls: false
      - name: tls
        port: 9093
        type: internal
        tls: true
        authentication:
          type: tls
      - name: external
        port: 9094
        type: nodeport
        tls: false
    storage:
      type: jbod
      volumes:
      - id: 0
        type: persistent-claim
        size: 40Gi
        deleteClaim: false
        class: nfs-storage
    config:
      offsets.topic.replication.factor: 1
      transaction.state.log.replication.factor: 1
      transaction.state.log.min.isr: 1
      auto.create.topics.enable: "false"
      enable.auto.commit: "false"
      
  zookeeper:
    replicas: 1
   # resources: 
   #   requests:
   ##     memory: 128Mi
    #    cpu: "100m"
    #  limits:
    #    memory: 256Mi
    #    cpu: "500m"    
    storage:
      type: persistent-claim
      size: 10Gi
      deleteClaim: false
      class: nfs-storage
  entityOperator:
    topicOperator: {}
    userOperator: {}