apiVersion: v1
kind: PersistentVolume
metadata:
  name: rabbitmq-demo-pv-on-mgp5.fors.ru
spec:
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-rabbitmq-demo-pv-on-mgp5.fors.ru
  local:
    path: /opt/persistence-rabbitmq-server
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - mgp5.fors.ru