### 1: Создание ЮЛ
#
POST http://localhost:8091/api/subject/create
Content-Type: application/json

{
  "subject_type": "UL",
  "name": "ОБЩЕСТВО С ОГРАНИЧЕННОЙ ОТВЕТСТВЕННОСТЬЮ \"ТОРГОВЫЙ ДОМ \"СЛОБОЖАНСКИЙ МЫЛОВАР\"",
  "short_name": "\"СЛОБОЖАНСКИЙ МЫЛОВАР\"",
  "opf": {
    "id": 12300
  },
  "inn": "3123320542",
  "kpp": "312301001",
  "ogrn": "1133123005707",
  "address": {
    "address": "БЕЛГОРОДСКАЯ ОБЛ, БЕЛГОРОД Г, КОММУНАЛЬНАЯ УЛ, Д. 18, ОФИС 208"
  }
}



### 2: Создание ЮЛ
#
POST http://localhost:8091/api/subject/create
Content-Type: application/json

{
  "subject_type": "UL",
  "name": "ОБЩЕСТВО С ОГРАНИЧЕННОЙ ОТВЕТСТВЕННОСТЬЮ \"ТОРГОВЫЙ ДОМ \"СИБИРСКИЙ МЫЛОВАР\"",
  "short_name": "\"СИБИРСКИЙ МЫЛОВАР\"",
  "opf": {
    "id": 12300
  },
  "inn": "5403036513",
  "kpp": "540301001",
  "ogrn": "1175476115429",
  "address": {
    "address": "НОВОСИБИРСКАЯ ОБЛ, НОВОСИБИРСК Г, БЕТОННАЯ УЛ, Д. 14, ОФИС 110"
  }
}

