apiVersion: v1
kind: Namespace
metadata:
  name: mcx

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: support-agreement-nginx-config
  namespace: mcx
data:
  default.conf: |
    server {
        listen      80;
        server_name localhost;

        location / {
             root /usr/share/nginx/html;
             try_files $uri $uri/ /index.html;
        }

        location /api/ {
            proxy_pass          http://support-agreement.mcx.svc.cluster.local/api/;
            proxy_set_header    Host    $host:$server_port;
            proxy_set_header    X-Real-IP   $remote_addr;
            proxy_cache_valid   200 302 401 404 10s;
        }


        error_page   500 502 503 504  /50x.html;
        location = /50x.html {
            root   /usr/share/nginx/html;
        }

        access_log  /var/log/nginx/support-agreement-frontend-access.log combined;
        error_log   /var/log/nginx/support-agreement-frontend-error.log debug;
    }
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: support-agreement-frontend
  namespace: mcx
spec:
  replicas: 3
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: mcx
      service: support-agreement-frontend
  template:
    metadata:
      name: mcx
      labels:
        app: mcx
        service: support-agreement-frontend
    spec:
      containers:
        - image: nexus.fors.ru:10442/mcx/support-agreement-frontend:latest
          name: support-agreement-frontend
          imagePullPolicy: Always
          ports:
            - name: liveness-port
              containerPort: 80
          volumeMounts:
            - name: support-agreement-nginx-config
              mountPath: /etc/nginx/conf.d/default.conf
              subPath: default.conf
      volumes:
        - name: support-agreement-nginx-config
          configMap:
            name: support-agreement-nginx-config
---

apiVersion: v1
kind: Service
metadata:
  name: support-agreement-frontend
  namespace: mcx
spec:
  type: NodePort
  selector:
    app: mcx
    service: support-agreement-frontend
  ports:
    - nodePort: 30557
      port: 80
      targetPort: 80
