apiVersion: v1
data:

  proxy-body-size: "5000m"
  proxy-read-timeout: "3600"
  proxy-send-timeout: "3600"
kind: ConfigMap
metadata:
    labels:
      app.kubernetes.io/component: controller
      app.kubernetes.io/name: ingress-nginx
      app.kubernetes.io/instance: ingress-nginx
      app.kubernetes.io/managed-by: Helm
      app.kubernetes.io/version: 0.44.0
      helm.sh/chart=ingress-nginx: 3.26.0

      
    name: ingress-nginx-controller
    namespace: ingress-nginx
    annotations:
      meta.helm.sh/release-name: "ingress-nginx"
      meta.helm.sh/release-namespace: "ingress-nginx"