apiVersion: v1
data:
  X-Different-Name: "true"
  X-Request-Start: t=${msec}
  X-Using-Nginx-Controller: "true"
  X-Forwarded-Server: $host
  X-Forwarded-For: $proxy_add_x_forwarded_for
  X-Forwarded-Port: $server_port
  X-Forwarded-Proto: $scheme
  X-Real-IP: $remote_addr
kind: ConfigMap
metadata:
  name: custom-headers
  namespace: ingress-nginx

