apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mavencache
  namespace: gitlab-managed-apps
spec:
  storageClassName: nfs-storage
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi