apiVersion: v1
kind: Namespace
metadata:
  name: mcx

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: support-agreement-frontend
  namespace: mcx
spec:
  replicas: 3
  selector:
    matchLabels:
      app: mcx
      service: support-agreement-frontend
  template:
    metadata:
      name: mcx
      labels:
        app: mcx
        service: support-agreement-frontend
    spec:
      containers:
        - image: nexus.fors.ru:10443/mcx/support-agreement-frontend:latest
          name: support-agreement-frontend
          imagePullPolicy: Always
          ports:
            - name: liveness-port
              containerPort: 80
---

apiVersion: v1
kind: Service
metadata:
  name: support-agreement-frontend
  namespace: mcx
spec:
  type: NodePort
  selector:
    app: mcx
    service: support-agreement-frontend
  ports:
    - nodePort: 30557
      port: 80
      targetPort: 80
