
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: certsrepo
  labels:
    app: certsrepo
spec:
  storageClassName: certsrepo-storage
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  volumeName: "certsrepo"
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: certsrepo
  labels:
    app: certsrepo
spec:
  storageClassName: certsrepo-storage
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: 172.29.7.227
    path: /var/nfs/fileshare

