apiVersion: v1
kind: Namespace
metadata:
  name: mcx-ingress

---

apiVersion: v1
kind: Secret
metadata:
  name: database-config
  namespace: mcx-ingress
stringData:
  HOST: mgp-db.fors.ru
  PORT: "6432"
  DATABASE: mgp_test
  USERNAME: postgres
  PASSWORD: postgres

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: control-limit
  namespace: mcx-ingress
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: control-limit
      service: control-limit
  template:
    metadata:
      name: mcx-ingress
      labels:
        app: control-limit
        service: control-limit
    spec:
      containers:
        - image: nexus.fors.ru:10442/mcx-ingress/control-limit:latest
          name: control-limit
          imagePullPolicy: Always
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8080
            initialDelaySeconds: 480
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8080
            initialDelaySeconds: 480
          ports:
            - name: liveness-port
              containerPort: 8080
          envFrom:
            - prefix: DB_
              secretRef:
                name: database-config
---

apiVersion: v1
kind: Service
metadata:
  name: control-limit
  namespace: mcx-ingress
spec:
  selector:
    app: control-limit
    service: control-limit
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
