apiVersion: v1
kind: Namespace
metadata:
  name: mcx

---  

apiVersion: v1
kind: Secret
metadata:
  name: database-config
  namespace: mcx
stringData:
  HOST: mgp-db.fors.ru
  PORT: "5432"
  DATABASE: mgp
  USERNAME: postgres
  PASSWORD: postgres

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: control-limit
  namespace: mcx
spec:
  replicas: 3
  selector:
    matchLabels:
      app: mcx
      service: control-limit
  template:
    metadata:
      name: mcx
      labels:
        app: mcx
        service: control-limit
    spec:
      containers:
        - image: nexus.fors.ru:10443/mcx/control-limit
          name: control-limit
          imagePullPolicy: Always
          ports:
            - name: liveness-port
              containerPort: 8080
          envFrom:
            - prefix: DB_
              secretRef:
                name: database-config
---

apiVersion: v1
kind: Service
metadata:
  name: control-limit
  namespace: mcx
spec:
  type: NodePort
  selector:
    app: mcx
    service: control-limit
  ports:
    - nodePort: 30555
      port: 80
      targetPort: 8080