---
    apiVersion: extensions/v1beta1
    kind: Ingress
    metadata:
      name: mcx-ingress-control-limit-frontend
      namespace: mcx
      annotations:
        nginx.ingress.kubernetes.io/rewrite-target: /$2
    spec:
      rules:
       - http:
          paths:
          - path: /control-limit-frontend2(/|$)(.*)
            backend:
              serviceName: control-limit-frontend2
              servicePort: 80