apiVersion: v1
kind: PersistentVolume
metadata:
  name: mavencache
  labels:
    app: mavencache
spec:
  storageClassName: mavencache-storage
  capacity:
    storage: 10Gi
  mountOptions:
    - nolock
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: 172.29.7.227
    path: /var/nfs/maven_cache