
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mavencache
  labels:
    app: mavencache
spec:
  storageClassName: mavencache-storage
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  volumeName: "mavencache"