apiVersion: databases.spotahome.com/v1
kind: RedisFailover
metadata:
  name: redisfailover
#  namespace: mgp
spec:
  sentinel:
    replicas: 2
    resources:
      requests:
        cpu: 100m
      limits:
        memory: 100Mi
  redis:
    replicas: 2
    resources:
      requests:
        cpu: 100m
        memory: 100Mi
      limits:
        cpu: 400m
        memory: 500Mi